namespace MAGIApp.Utils
{
    public static class UserDetails
    {
        public static string PhoneTypeID { get; set; }
        public static string PhoneTypeID2 { get; set; }
        public static string PhoneType_pKey { get; set; }
        public static string PhoneType2_pKey { get; set; }
        public static string Image { get; set; }
        public static string Account_pkey { get; set; }
        public static string ContactName { get; set; }
        public static string Firstname { get; set; }
        public static string MiddleName { get; set; }
        public static string Lastname { get; set; }
        public static string Title { get; set; }
        public static string UL { get; set; }
        public static string Activated { get; set; }
        public static string AccountStatus_pkey { get; set; }
        public static string ActivationDate { get; set; }
        public static string LastLogin { get; set; }
        public static string LastViewedEvent_pKey { get; set; }
        public static string Email { get; set; }
        public static string Email2 { get; set; }
        public static string Phone { get; set; }
        public static string Phone2 { get; set; }
        public static string AllowText { get; set; }
        public static string AllowEmail { get; set; }
        public static string AllowCall { get; set; }
        public static string Address1 { get; set; }
        public static string Address2 { get; set; }
        public static string City { get; set; }
        public static string Department { get; set; }
        public static string State_pKey { get; set; }
        public static string ZipCode { get; set; }
        public static string Comment { get; set; }
        public static string StaffMember { get; set; }
        public static string PrioritySpeaker { get; set; }
        public static string GeneralInterestInBeingSpeaker { get; set; }
        public static string PersonalBio { get; set; }
        public static string AboutMe { get; set; }
        public static string Degrees { get; set; }
        public static string Nickname { get; set; }
        public static string URL { get; set; }
        public static string LastProfileUpdate { get; set; }
        public static string SkypeAddress { get; set; }
        public static string LastSpeakerProfileUpdate { get; set; }
        public static string SalutationID { get; set; }
        public static string CountryID { get; set; }
        public static string OrganizationID { get; set; }
        public static string StateID { get; set; }
        public static string OtherState { get; set; }
        public static string accountstatusID { get; set; }
        public static string PhotoApproved { get; set; }
        public static string HasPhoto { get; set; }
        public static string LastApprovedDate { get; set; }
        public static string MostRecentExternalAccess { get; set; }
        public static string OrganizationType_pKey { get; set; }
        public static string OrganizationTypeID { get; set; }
        public static string Phone1CC { get; set; }
        public static string Phone2CC { get; set; }
        public static string Phone1Ext { get; set; }
        public static string Phone2Ext { get; set; }
        public static string VIP { get; set; }
        public static string TimezonePKey { get; set; }
        public static string PhoneticName { get; set; }
        public static string Timezone { get; set; }
        public static string Member { get; set; }
        public static string Suffix_pkey { get; set; }
        public static string LicenseNumber { get; set; }
        public static string LicenseState { get; set; }
        public static string LicenseTypeID { get; set; }
        public static string LinkedInProfile { get; set; }
        public static string showJournal { get; set; }
        public static string strEmailUsed { get; set; }
        public static string ParentOrganization_pKey { get; set; }
        public static string Salutation_pKey { get; set; }
        public static string Country_pKey { get; set; }
        public static string TimeZone { get; set; }
        public static string LicenseType { get; set; }
        public static string Suffix { get; set; }
        public static string GetJournal { get; set; }
        public static string EmailUsed { get; set; }
        public static string userRole { get; set; }
    }
}
